# Introducción
### Variables

In [2]:
r = 5
pi = 3.141592

In [6]:
area_circulo = r**2* pi

In [7]:
print(area_circulo)

78.5398

### Listas

In [ ]:
# Definimos una lista de notas de un exámen
marks = [8.5, 9.0, 7.5, 10.0, 6.5]

# Función sum() "suma" y función len() longitud de la lista.
mean = sum(marks)/len(marks)

print("La nota media de la clase es:", mean)

La nota media de la clase es: 8.3

In [3]:
marks[0]

8.5

In [ ]:
# Vamos a extraer una sublista de la lista "marks" entre el elemnto 1 y 3
sub_marks = marks[1:4]

print(sub_marks)

[9.0, 7.5, 10.0]

Vamos a ver ahora el por qué de que este tipo de listas no sean idóneas para trabajar con ellas en Data Science
y necesitemos librerías específicas con estructuras de datos que nos permitan trabajar de forma óptima en esto.

In [ ]:
# Intentamos multiplicar la lista "marks" por dos
double_marks = marks*2

print(double_marks)

[8.5, 9.0, 7.5, 10.0, 6.5, 8.5, 9.0, 7.5, 10.0, 6.5]

## Numpy

La operación que hemos realizado no ha multiplicado los elementos de la lista "marks" por 2, sino que,
debido a la forma que tiene python de ver la listas, como un objeto en memoria y no algebraico, lo que ha hecho es duplicar la lista.

Para atajar este problema se creó la biblioteca Numpy, para poder trabajar con álgebra lineal a través de su estructura de "array"
con la que podremos definir vectores y matrices y trabajar con ellos de forma cómoda.

In [ ]:
# Importamos la biblioteca Numpy
import numpy as np

# Convertimos la lista "marks" en un array de numpy
marks_vector = np.array(marks)

# Operamos con una sitaxis similar a la que hemos intentado utilizar previamente
double_marks_vector = marks_vector * 2

# Imprimimos en pantalla el resultado de la operción
print("Las notas iniciales eran: ", marks_vector)
print("Las notas duplicadas son: ", double_marks_vector)

Las notas iniciales eran:  [ 8.5  9.   7.5 10.   6.5]
Las notas duplicadas son:  [17. 18. 15. 20. 13.]

Una vez visto cómo trabajan, brevemente, los arrays unidimensionales (vectores) de numpy vamos a ver cómo trabajar con arrays bidimensionales, o matrices. 
Este tipo de estructuras de datos se corresponden con los datasets comunes en los que cada fila es una medición de algún elemento de una población (o registro),
y cada columna representa los distintos registros de una variable medible, sea del tipo que sea cualitativa o cuantitativa (booleana, de enteros, decimal pto. flotante, etc).

In [ ]:
# Definición de una matriz como lista de listas
A_matrix = np.array([
    [10, 20, 30], # Fila 0 (row 1)
    [40, 50, 60]  # Fila 1 (row 2)
])

print("La matriz definida es: ", A_matrix)
print("\nLa dimensión de la matriz es: ", A_matrix.shape) # array.shape devuelve una dupla con las dimensiones de la matriz

La matriz definida es:  [[10 20 30]
 [40 50 60]]

La dimensión de la matriz es:  (2, 3)

In [9]:
#Imprimimos un dato específico de la matriz "A_matrix"
print(A_matrix[1, 1])

50

In [10]:
#Vamos a sustraer una parte de una matriz, en este caso, la segunda columna
column_2 = A_matrix[:, 1]

print("La segunda columna es: ", column_2)

La segunda columna es:  [20 50]

In [11]:
#Vamos a sustraer una parte de una matriz, en este caso, la segunda columna
column_1 = A_matrix[:, 0]

print("La segunda columna es: ", column_1)

La segunda columna es:  [10 40]

En la siguiente caja de código vamos a crear una máscara booleana, esto es una condición, verdadera o 
falsa y se la vamos a aplicar a la matriz para filtrar datos en base a la condición de la máscara.

In [ ]:
#Matriz:
# [10, 20, 30]
# [40, 50, 60]

#Creamos la condición y la almacenamos en una máscara booleana
mask = A_matrix > 25

print("1. Matriz de booleanos: \n", mask)

#Filtrramos los datos de la matriz en base a la matriz booleana que hemos generado
filtered_A_matrix = A_matrix[mask]

print("\nLos elementos que cumplen la condición son: \n", filtered_A_matrix)
#Pérdida de dimensionalidad por filtrado

1. Matriz de booleanos:
 [[False False  True]
 [ True  True  True]]

Los elementos que cumplen la condición son:
 [30 40 50 60]

Pero en el mundo real, los datos son sucios. Si trabajamos con datos de pacientes, 
tendremos una columna con su Nombre (texto), otra con su Edad (entero), otra con su Peso (decimal) 
y otra con si está Sano (booleano). NumPy no está diseñado para mezclar tipos de datos en una misma 
estructura.

Para eso usamos Pandas, la biblioteca que introduce el concepto de DataFrame, que puedemos imaginarlo 
exactamente como una hoja de cálculo de Excel o una tabla de base de datos hipervitaminada. 
Por debajo, cada columna de un DataFrame es un vector de NumPy.

## Pandas
#### Creación de un Dataframe

In [15]:
#Creación de un DataFrame de Pandas
import pandas as pd

#Creamos un diccionario con los datos de 3 pacientes
datos_clinicos = {
    'paciente': ['Ana', 'Carlos', 'Luis'],
    'edad': [28, 45, 32],
    'presion_arterial': [120.5, 140.2, 118.0],
    'apto': [True, False, True]
}

#Creación del DataFrame de pandas a partir del diccionario de python creado
df = pd.DataFrame(datos_clinicos)

#Visualización del DataFrame, suficiente en jupyter, no hace falta print
df

  paciente  edad  presion_arterial   apto
0      Ana    28             120.5   True
1   Carlos    45             140.2  False
2     Luis    32             118.0   True

### .iloc() 
#### Acceso a una variable mediante su posición numérica

In [20]:
#Vamos a acceder una de las variables
fila_nombre_paciente = df.iloc[:, 0]

print("Los nombres de los pacientes son: \n")
fila_nombre_paciente

Los nombres de los pacientes son:

0       Ana
1    Carlos
2      Luis
Name: paciente, dtype: object

#### Fintrado en Pandas 
La sintaxis de las máscaras es igua que la de Numpy pero no perdemos la dimensionalidad.

In [21]:
#Creación de la máscara en base a una condición sobre la variable "edad" del DataFrame "df"
#Acceso a una variable mediante una etiquetas
condicion = df['edad'] > 30

#Filtramos el DataFrame original con la condición que hemos impuesto
pacientes_mayores = df[condicion]

#Mostramos el resutado
pacientes_mayores

  paciente  edad  presion_arterial   apto
1   Carlos    45             140.2  False
2     Luis    32             118.0   True

### .set_index
#### Cambio de índice tabular en un DataFrame

In [22]:
#Cambiamos del índice automático 0, 1, 2 a un índice dado por el nombre de los pacientes
df_pacientes = df.set_index('paciente')

#Mostramos el resultado
df_pacientes

          edad  presion_arterial   apto
paciente
Ana         28             120.5   True
Carlos      45             140.2  False
Luis        32             118.0   True

### .loc
#### Búsqueda de datos mediante etiquetas .loc['fila', 'columna']

In [23]:
#Extraemos la información del registro 'Carlos'
df_pacientes.loc['Carlos']

edad                   45
presion_arterial    140.2
apto                False
Name: Carlos, dtype: object

In [ ]:
#Extraemos la información de una celda específica
presion_ana = df_pacientes.loc['Ana','presion_arterial']

print("La presión de Ana es: ", presion_ana)

La presión de Ana es:  120.5

In [27]:
#Extraer una submatriz (slicing) con nombres
submatriz = df_pacientes.loc['Ana':'Luis', ['edad', 'apto']]
submatriz

          edad   apto
paciente
Ana         28   True
Carlos      45  False
Luis        32   True

Filtrado de registros con la condición dentro de .loc[]

In [28]:
#Extraemos la presión arterial de los pacientes con más de 30 años:
df_pacientes.loc[df_pacientes['edad']>30, 'presion_arterial']

paciente
Carlos    140.2
Luis      118.0
Name: presion_arterial, dtype: float64